### PR TITLE
add "hasUndo" and "hasRedo" observable property for render button in ui

### PR DESCRIPTION
**Pull request by meded90**

### CODE REVIEW

**Review by pimterry — APPROVED** [review]
Thanks @meded90, this looks great! Nice improvement. I've made some tiny style tweaks but otherwise this is all good :+1:

When you have a sec, could you sign the CLA please? It's [here](https://cla-assistant.io/httptoolkit/mobx-shallow-undo?pullRequest=1). This just makes it explicit that you're giving the project a license to use this contributed code, and that you promise you're legally allowed to do so. Once that's done the license/cla check here will pass.

**Comment by pimterry** [comment]
@SocketSecurity ignore @swc/core@1.3.1

**Comment by meded90** [comment]
I signed CLA

**Comment by pimterry** [comment]
Thats perfect, thanks @meded7! I'll create a new release and publish this shortly.

**Pull request merged**
